# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rafael Lins
description: >- # this means to ignore newlines until "baseurl:"...  com temas de informática, viagens, músicas e o que mais puder compartilhar :)
  Site pessoal
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leafarlins.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: leafarlins
github_username:  leafarlins

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag


permalink: none
#paginate: 6
#paginate_path: /page:num/

#social
twitter: http://twitter.com/@leafarlins
github: http://github.com/leafarlins
linkedin: https://www.linkedin.com/in/rafael-lins-bb757272/
email: leafarlins@gmail.com

# Sass style
sass:
  style: compressed

# Menus multilang
t:
  en:
    home:
      name: "Home"
      url: "/en/"
    about:
      name: "About"
      url: "/about/"
    contato:
      name: "Contact"
      url: "/contact/"
  fr:
    home:
      name: "Accueil"
      url: "/fr/"
    about:
      name: "À propos"
      url: "/a-propos/"
    contato:
      name: "Contate"
      url: "/a-propos/"
  pt:
    home:
      name: "Início"
      url: "/"
    about:
      name: "Sobre"
      url: "/a-propos/"
    contato:
      name: "Contato"
      url: "/contato/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
